// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  usersSidebar: [{type: 'autogenerated', dirName: 'users'}],
  developersSidebar: [{type: 'autogenerated', dirName: 'developers'}],
};

module.exports = sidebars;
